### ISSUE TITLE
NodaTime v3 support

### ISSUE THREAD

**Issue by DmitryMak** [nodatime/nodatime.serialization#65]
Looks like NodaTime 3 is not supported while nuget package claims that it is. This results in a runtime binding resolution exception:

```
System.IO.FileLoadException: Could not load file or assembly 'NodaTime, Version=2.4.8.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' 
or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NodaTime, Version=2.4.8.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1'

```

From nodatime.serialization.jsonnet.nuspec:
```
<group targetFramework=".NETStandard2.0">
    ...
    <dependency id="NodaTime" version="2.4.8" exclude="Build,Analyzers" />
</group>
```

My understanding is that "2.4.8" means 2.4.8 or higher (minimum version, inclusive). And instead it should be something like "(,2.4.8]" (maximum version, inclusive). In which case msbuild should issue a warning when building code that references both NodaTime (v3) and NodaTime.Serialization.JsonNet. So a manual binding redirect can be added to avoid runtime exception. At least until NodaTime.Serialization.JsonNet starts referencing NodaTime v3 package.

**Comment by jskeet** [comment]
It should probably be `[2.4.8,3.0.0)` - it's definitely not a *maximum* version, as it won't work if you try to use it with NodaTime 1.0.0 for example. In general I wish that dependencies followed SemVer by default - 2.4.8 *should* mean `[2.4.8, 3.0.0)` automatically in order to follow SemVer. But I think very few libraries really specify their dependencies that way.

In general I'd actually expect the serialization libraries in this repo to work with NodaTime 3.x anyway, as they're not affected by the breaking changes in 3.0. But I'll release a new major version of the serialization libraries targeting 3.x when I get round to it.

Note that with .NET Core it should all just work out of the box - it's only when using .NET Framework that you need assembly binding redirects.

**Comment by jskeet** [comment]
I've now pushed packages targeting NodaTime 3.0.
