### ISSUE TITLE
Security issue NodaTime.Serialization.SystemTextJson

### ISSUE THREAD

**Issue by kpwbo** [nodatime/nodatime.serialization#84]
Hello,

We use NodaTime.Serialization.SystemTextJson@1.0.0 in some of our projects. We used Snyk to analyse our dependencies and to find vulnerabilities. Snyk reported a vulnerability in one of the dependencies of NodaTime.Serialization.SystemTextJson@1.0.0. The dependency System.Text.Encodings.Web@4.7.0 (used by System.Text.Json@4.7.1, which is in turn used by NodaTime.Serialization.SystemTextJson@1.0.0) introduces the following vulnerability: https://www.cve.org/CVERecord?id=CVE-2021-26701

It is my understanding that this vulnerability has been fixed in the upstream packages. Looking at the file NodaTime.Serialization.SystemTextJson.csproj in the main branch (https://github.com/nodatime/nodatime.serialization/blob/a4a0333f6f723c7757c4e114a95d9debfba54f49/src/NodaTime.Serialization.SystemTextJson/NodaTime.Serialization.SystemTextJson.csproj), it seems that the dependency is only defined explicitly for netstandard2.0. For netcoreapp3.1, it is not (so the runtime version will be used I think). I believe this would fix the vulnerability for our projects (we use net6.0) and other projects that target netcoreapp3.1 and further.

However, there has been no release of the NuGet package based on this version of NodaTime.Serialization.SystemTextJson.csproj yet. The latest release uses this version: https://github.com/nodatime/nodatime.serialization/blob/43299d06f284f064f083bdf91ccbf4d95903df9f/src/NodaTime.Serialization.SystemTextJson/NodaTime.Serialization.SystemTextJson.csproj. In this version, the dependency is always defined explicitly.

If my understanding is correct, releasing an up-to-date NuGet package should fix the vulnerability for some contexts. If that is indeed the case, would it be possible for you to do it?

Thank you in advance.

**Comment by jskeet** [comment]
I'm happy to get to this when I can, but it's not likely to be soon. In the meantime, I'd expect you to be able to fix this in your application just by taking an explicit dependency on an appropriate version of System.Text.Json yourself.

**Comment by kpwbo** [comment]
Thanks for the quick reply and the workaround!

**Comment by jskeet** [comment]
This isn't quite as straightforward as I'd hoped, due to https://github.com/dotnet/runtime/issues/61602. If we depend on the latest version of System.Text.Json (or anything from 6.0.0) that breaks any netcoreapp3.1 builds with warnings-as-errors.
So for the moment it looks like I'm stuck on 5.0.2, which works.

When netcoreapp3.1 goes out of support (at the end of 2022) I'll probably create a new version targeting net6.0 instead. But for the moment, at least the newer (5.0.2) version should avoid this issue.
I'll do a release when I can find some more time, possibly looking at other small things I can clean up at the same time.
